openapi: 3.0.1
info:
  title: Sample API
  description: Sample API for Spring Boot
  version: 0.0.1
servers:
  - url: http://localhost:8080

paths:
  /api/contacts:
    post:
      summary: Creates a contact.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '201':
          description: Created
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
    delete:
      summary: Deletes a contact.
      parameters:
        - name: id
          in: query
          required: true
          description: The ID of the user to delete.
          schema:
            $ref: '#/components/schemas/Person'
      responses:
        '200':
          description: A user object.
  /api/contacts/{sortingtype}:
    get:
      summary: Returns sorted list of contacts.
      parameters:
        - name: sortingtype
          in: path
          required: true
          description: The type of sorting
          schema:
            type: String
      responses:
        '200':
          description: A user object.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'

components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        surname:
          type: string
        number:
          type: string